### ISSUE TITLE
Varios fallos que hay que modificar y/o arreglar

### ISSUE THREAD

**Issue by JoseLomero** [rayaalmudena/qui_es_qui#4]
- [x] REFACTORIZAR ESOS MILLONES DE IF Y ELSE IF QUE HAY EN EL JS
- [x] REFACTORIZAR EL MODO EASY Y VERY EASY
- [x] Cuando activas el modo Easy o Very Easy (a parte de que no funciona bien) la primera carta nunca se girará con lo cual (a parte de que va mal) *casi* nunca podrás ganar
- [x] Cuando ganas/pierdes, el contador de volteo debería desaparecer y ni el tiempo ni nada debería sumarse

- [x] Añadir modal en el Easter Egg para que se sepa que se ha activado
- [x] Cuando cierras el modal de haber ganado/perdido, la página debe hacer un refresh
- [x] Gestionar el final del juego
- [x] Habilitar de nuevo el contador de clicks, y que funcione correctamente
- [x] QUITAR EL *no tiene gafas*

Iré añadiendo más cosas conforme vaya dándome cuenta de errores

**Comment by rayaalmudena** [comment]
El refresh esta despues de darle ok al modal del easter egg
location.reload(true);
